### PR TITLE
Added watchat to readme

### PR DESCRIPTION
**Pull request by WatChat-TV**
...at the end of the paragraph this time.

### CODE REVIEW

**Review by PopeyeTheSai10r — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Comment by freearhey** [comment]
@WatChat-TV Sorry, but why did you link to the website and not the Google Play page?

@PopeyeTheSai10r @BellezaEmporium Have you guys run the app itself?

**Comment by BellezaEmporium** [comment]
> @WatChat-TV Sorry, but why did you link to the website and not the Google Play page?
> 
> @PopeyeTheSai10r @BellezaEmporium Have you guys run the app itself?
> 

They say they aren't on Google Play.

**Comment by freearhey** [comment]
@BellezaEmporium then where are these reviews coming from:

image
https://www.watchat.online/

**Comment by WatChat-TV** [comment]
Hello guys,
thanks for having us, those reviews come from Google Play and are from the times when we were still there.
We opted out google for many reasons and we do not plan to get in there again with WatChat, some of the reasons are:

1) Sticking with google publication rules and taking care of the google play account is a job itself, especially doing the so called ASO to stay visible in there. 
2) We tried to strip away tracking code from the app (ie google services) but that was not allowed if publishing in gplay.
3) Google forces continuous, often unneeded updates of many libraries, deprecating whole branches and introducing new ways of doing stuff often not respecting backward compatibility (there is a big debate in android community going on since many years). 
3) We are considering switching to FOSS the whole or part of the codebase.
4) We are getting interested in non tracking OS like GrapheneOS ad CalixOs.

In general we are interested in supporting IPTV projects and contributing to the API. 
Thanks for having us.

Joe

**Comment by WatChat-TV** [comment]
Also a quick tour of the ways we can start to contribute/interact with you (ie to whom propose things before branching/requesting pulls) would be greatly appreciated. Thanks.

Joe

**Comment by freearhey** [comment]
To me, this just means that the current version of the app has not been tested for malicious code. And given that it is also impossible to check reviews, I would prefer that we remove the link to the app from the list, at least until the app code is published.

**Comment by WatChat-TV** [comment]
Allow me to disagree,
All the apk that are installed on an android phone can nowadays be scanned by many services, including one by google itself among the others that starts automatically at install time (https://support.google.com/googleplay/answer/2812853?hl=en).
The app is published in many stores that are not google but offer quality and security check (such as APKPure and many others).
I noticed that in the list itself there are other apps distributed directly and I personally think this is a great  thing (are you going to remove them all or what?)
Last but not least a question for Aleksandr:  do you guys think that a code that is not distributed through google contains malicious code and one that is distributed through google does not?

**Comment by WatChat-TV** [comment]
Just saw you removed the apps that are not distributed by google. 
We express our strong disagree on that decision, we think this does not promote freedom for developers and users to decide what to install and from where and what to publish and where.

**Comment by freearhey** [comment]
> are you going to remove them all or what?

The changes affect only self-hosted closed source apps. Open source apps as well as links to verified stores (including APKPure) will not be affected.

> do you guys think that a code that is not distributed through google contains malicious code and one that is distributed through google does not?

No, of course not.

**Comment by WatChat-TV** [comment]
I am going to add the apkpure link then, 
For the records I still I do not agree with the policy accepting only app distributed through stores.
In our opinion app stores are one of the limits to android devs (and users) freedom.

**Pull request merged**
