### PR TITLE
Remove "Providers" list

### LINKED ISSUE #166: Don't show any paid providers
The ones that are listed are clearly illegal and it comes across as a recommendation from the @iptv-org.

The org makes a large effort to maintain it's legality in other repos, including blacklisting specific channels being added to the DB and responding the DMCA notices.

In my opinion this list should be a one stop shop for developers and power users building for and using IPTV, not an advertisement for black market operators.

### PR DESCRIPTION
**Pull request by BellezaEmporium**
After thinking for a while, I think the "providers" section isn't useful.

Adresses and closes #166

### CODE REVIEW

**Comment by freearhey** [comment]
I personally do not see the need to remove this list.

**Review by freearhey — COMMENTED** [review]
I personally do not see the need to remove this list.

**Comment by BellezaEmporium** [comment]
> I personally do not see the need to remove this list.

It's unfitting as we have tons of developer tools and this getting in makes it seems to be rather off.

**Comment by mikhoul** [comment]
> it seems to be rather off

I agree, imo a good compromise could be to point users with links to groups/forums/ specialized in IPTV gray market providers instead of directly to specific providers. :octocat:

**Comment by PopeyeTheSai10r** [comment]
I am all in agreement of the removal of Paid Providers. 
I think the free ones can stay.

**Review by PopeyeTheSai10r — DISMISSED** [review]

**Review by PopeyeTheSai10r — APPROVED** [review]

**Review by RevGear — APPROVED** [review]

**Pull request merged**
