### PR TITLE
Add IPTV-Player application link

### PR DESCRIPTION
**Pull request by Mravuri96**
Website is still early in development, but works. Pr's are welcome.

Applications source code can be found here [IPTV-Player,](https://github.com/Mravuri96/IPTV-Player) in the source branch.

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Comment by Mravuri96** [comment]
@freearhey any reason as to why this app was placed in the providers section and not the Apps section?

**Comment by freearhey** [comment]
@Mravuri96 there is no way to run your own playlist in the app.

**Comment by Mravuri96** [comment]
> @Mravuri96 there is no way to run your own playlist in the app.

Thanks for the response, I'll ping you again, if I add that functionality.

**Comment by freearhey** [comment]
Moved the link to Web Apps section.

**Comment by rene32** [comment]
dobriden could bistemi send iptv codi in Slovak and in the Czech pogrami I would very much thank you

**Pull request merged**
