### PR TITLE
add globalfreetv.com

### PR DESCRIPTION
**Pull request by keith666666**
add https://globalfreetv.com/

image

### CODE REVIEW

**Comment by freearhey** [comment]
image

**Comment by keith666666** [comment]
> https://globalfreetv.com/
Would you might to try again? it seems like a network unstable issue
image

**Comment by freearhey** [comment]
@keith666666 Same result.

**Comment by keith666666** [comment]
> @keith666666 Same result.
There appears to be a performance issue, but the page should eventually load. 
Sorry to ask, but is it possible for you to switch the network and try again?

image

**Comment by freearhey** [comment]
@keith666666 Doesn't work even through VPN, and in the console it shows the following:

```
Failed to load resource: net::ERR_TIMED_OUT
660-8975cd119bd213fd.js:1 Error fetching data: TypeError: Failed to fetch
    at c (919-fa772b21a790228d.js:1:24450)
    at page-8024055dbd15dcd9.js:1:13291
    at page-8024055dbd15dcd9.js:1:13468
    at aW (e6e143be-ef613f622f3d7c01.js:1:73241)
    at oe (e6e143be-ef613f622f3d7c01.js:1:84682)
    at ol (e6e143be-ef613f622f3d7c01.js:1:85320)
    at or (e6e143be-ef613f622f3d7c01.js:1:85204)
    at ol (e6e143be-ef613f622f3d7c01.js:1:86265)
    at or (e6e143be-ef613f622f3d7c01.js:1:85204)
    at ol (e6e143be-ef613f622f3d7c01.js:1:86265)
window.console.error @ 660-8975cd119bd213fd.js:1
(anonymous) @ page-8024055dbd15dcd9.js:1
global-free-tv-api.leontloveless.workers.dev/popular-channels:1 
        
        
       Failed to load resource: net::ERR_TIMED_OUT
global-free-tv-api.leontloveless.workers.dev/countries:1 
        
        
       Failed to load resource: net::ERR_TIMED_OUT
```

**Comment by keith666666** [comment]
> @keith666666 Doesn't work even through VPN, and in the console it shows the following:
> 
> ```
> Failed to load resource: net::ERR_TIMED_OUT
> 660-8975cd119bd213fd.js:1 Error fetching data: TypeError: Failed to fetch
>     at c (919-fa772b21a790228d.js:1:24450)
>     at page-8024055dbd15dcd9.js:1:13291
>     at page-8024055dbd15dcd9.js:1:13468
>     at aW (e6e143be-ef613f622f3d7c01.js:1:73241)
>     at oe (e6e143be-ef613f622f3d7c01.js:1:84682)
>     at ol (e6e143be-ef613f622f3d7c01.js:1:85320)
>     at or (e6e143be-ef613f622f3d7c01.js:1:85204)
>     at ol (e6e143be-ef613f622f3d7c01.js:1:86265)
>     at or (e6e143be-ef613f622f3d7c01.js:1:85204)
>     at ol (e6e143be-ef613f622f3d7c01.js:1:86265)
> window.console.error @ 660-8975cd119bd213fd.js:1
> (anonymous) @ page-8024055dbd15dcd9.js:1
> global-free-tv-api.leontloveless.workers.dev/popular-channels:1 
>         
>         
>        Failed to load resource: net::ERR_TIMED_OUT
> global-free-tv-api.leontloveless.workers.dev/countries:1 
>         
>         
>        Failed to load resource: net::ERR_TIMED_OUT
> ```
Just run a test with page speed, it seems fine
https://pagespeed.web.dev/analysis/https-www-globalfreetv-com/3i1sbqzug7?form_factor=desktop
image

**Comment by EatPrilosec** [comment]
its working fine for me

**Review by PopeyeTheSai10r — DISMISSED** [review]

**Comment by BellezaEmporium** [comment]
Works on my side too.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by Dum4G** [comment]
image

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
